In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.full((3,4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
np.arange(0,100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [8]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [9]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
myarr.shape

(4, 3)

In [11]:
myarr.size

12

In [12]:
myarr.ndim

2

In [13]:
myarr.dtype

dtype('int64')

In [14]:
myarr.astype(np.float32)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)